version: "3.7"

services:
        php-apache:
                container_name:
                        webserver
                image:
                        webserver
                environment: 
                        - DOMAIN=CLUSTER
                build:
                        context: ./php-apache
                ports:
                        - 80:80
                volumes:
                        - ./html:/var/www/html
                        - ./conf:/var/www/conf
                links:
                        - 'mariadb'
                restart:
                        always
                networks:
                        - my-net
                environment:
                        dbhost: "db"
                        be: "symfony"

        symfony:
                container_name:
                        symfony
                image:
                        symfony
                environment: 
                        - DOMAIN=CLUSTER
                build:
                        context: ./symfony
                ports:
                        - 8080:80
                volumes:
                        - ../dynacert-server:/var/dynacert-server
                links:
                        - 'mariadb'
                restart:
                        always
                networks:
                        - my-net
                environment:
                        dbhost: "db"




        mariadb:
                container_name:
                        db
                image:
                        db
                ports:
                        - 3306:3306
                build:
                        context: ./mariadb
                volumes:
                        - ./mariadb_data:/var/lib/mysql
                networks:
                        - my-net

networks:
  my-net:
    driver: bridge