export default {
    'simpletext': {
        showSimpleText: true,
        showMultilineText: false,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: true,
        typeOfContent: true,
    },
    'email': {
        showSimpleText: true,
        showMultilineText: false,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: true,
        typeOfContent: false,
    },
    'tel': {
        showSimpleText: true,
        showMultilineText: false,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: true,
        typeOfContent: false,
    },
    'multilinetext': {
        showSimpleText: false,
        showMultilineText: true,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'multiple': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: true,
        showRowOptionValue: true,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'checkbox': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: true,
        showRowOptionValue: true,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'dropdown': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: true,
        showRowOptionValue: true,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'linearscalar': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: true,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'multiplegrid': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: true,
        showRowOptionValue: true,
        showColOptionValue: true,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'checkboxgrid': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: true,
        showRowOptionValue: true,
        showColOptionValue: true,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'date': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: true,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'time': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: true,
        rememberOnBrowser: false,
        typeOfContent: false,
    },
    'note': {
        showSimpleText: false,
        showMultilineText: false,
        showMinMax: false,
        showRowOptionValue: false,
        showColOptionValue: false,
        showDate: false,
        showTime: false,
        rememberOnBrowser: false,
        typeOfContent: false,
    }
}